/// Flutter icons DeanInstituteIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  DeanInstituteIcons
///      fonts:
///       - asset: fonts/DeanInstituteIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class DeanInstituteIcons {
  DeanInstituteIcons._();

  static const _kFontFam = 'DeanInstituteIcons';
  static const String? _kFontPkg = null;

  static const IconData library_icon = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData course_icon = IconData(
    0xe801,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData bootcamp_icon = IconData(
    0xe802,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
